### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#6]
Nothing in particular that causes the crash, it just crashes randomly with this error
```
org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glTexCoordPointer(GL11.java:3136)
	at nw.draw(Tessellator.java:140)
	at net.skidcode.gh.fallingleaves.particle.LeafParticle.a(LeafParticle.java:65)
	at dn.a(EffectRenderer.java:104)
	at px.a(EntityRenderer.java:923)
	at px.b(EntityRenderer.java:828)
	at EntityRendererProxy.b(EntityRendererProxy.java:14)
	at overrideapi.proxy.EntityRendererProxy.b(EntityRendererProxy.java:19)
	at net.minecraft.client.Minecraft.run(Minecraft.java:622)
	at java.lang.Thread.run(Thread.java:750)
org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glTexCoordPointer(GL11.java:3136)
	at nw.draw(Tessellator.java:140)
	at mk.a(LoadingScreenRenderer.java:89)
	at mk.d(LoadingScreenRenderer.java:55)
	at net.minecraft.client.Minecraft.a(Minecraft.java:1346)
	at net.minecraft.client.Minecraft.a(Minecraft.java:1336)
	at net.minecraft.client.Minecraft.a(Minecraft.java:1332)
	at net.minecraft.client.Minecraft.run(Minecraft.java:672)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by MasterSlenderTR** [comment]
The issue has been fixed in PRE2
