### ISSUE TITLE
Seasons mod crash

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#7]
Every once in a while (10-15mins) the game crashes with this exception
```
java.lang.NoSuchFieldError: r
	at mod_seasons.desertHeat(mod_seasons.java:476)
	at mod_seasons.seasonTick(mod_seasons.java:452)
	at mod_seasons.OnTickInGame(mod_seasons.java:285)
	at ModLoader.OnTick(ModLoader.java:814)
	at EntityRendererProxy.b(EntityRendererProxy.java:15)
	at overrideapi.proxy.EntityRendererProxy.b(EntityRendererProxy.java:19)
	at net.minecraft.client.Minecraft.run(Minecraft.java:622)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by MasterSlenderTR** [comment]
The issue has been fixed in PRE2
